// src/components/product/ProductCard.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { ShoppingCart } from 'lucide-vue-next';
import type { Product } from '@/types/product';
import { useCartStore } from '@/store/useCartStore';

const props = defineProps<{
  product: Product;
}>();

const router = useRouter();
const cartStore = useCartStore();
const isLoaded = ref(false);

function handleAddToCart(e: Event) {
  e.stopPropagation();
  e.preventDefault();
  cartStore.addItem(props.product);
}

function handleViewDetails() {
  router.push(`/product/${props.product.id}`);
}
</script>

<template>
  <div
    class="overflow-hidden border-none shadow-sm hover:shadow-md transition-all duration-300 group rounded-2xl bg-white flex flex-col justify-between cursor-pointer"
    @click="handleViewDetails"
  >
    <div>
      <!-- Image container -->
      <div class="relative aspect-square overflow-hidden bg-secondary/20">
        <img
          :src="product.image"
          :alt="product.name"
          @load="isLoaded = true"
          class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
          :class="isLoaded ? 'opacity-100' : 'opacity-0'"
        />

        <div
          v-if="!isLoaded"
          class="absolute inset-0 flex items-center justify-center bg-secondary/10 animate-pulse"
        >
          <span class="text-xs text-muted-foreground">Carregando...</span>
        </div>

        <span
          class="absolute top-3 left-3 bg-white/90 text-primary text-[10px] uppercase font-bold py-0.5 px-2 rounded-md shadow-sm"
        >
          {{ product.category }}
        </span>
      </div>

      <!-- Info -->
      <div class="p-4">
        <h3 class="font-bold text-base mb-1 line-clamp-1 group-hover:text-primary transition-colors">
          {{ product.name }}
        </h3>
        <p class="text-muted-foreground text-xs line-clamp-2 mb-3 h-8">
          {{ product.shortDescription }}
        </p>
        <div class="flex items-center justify-between">
          <span class="text-lg font-bold text-primary">
            R$ {{ product.price.toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }}
          </span>
        </div>
      </div>
    </div>

    <!-- Actions -->
    <div class="p-4 pt-0 flex gap-2">
      <button
        type="button"
        @click.stop="handleViewDetails"
        class="flex-1 py-2 px-3 text-xs font-semibold rounded-xl border border-primary/20 text-primary hover:bg-primary/10 transition-colors text-center"
      >
        Ver detalhes
      </button>
      <button
        type="button"
        @click="handleAddToCart"
        class="bg-primary text-white hover:bg-primary/90 h-9 w-9 flex items-center justify-center rounded-xl shadow-sm transition-colors"
        title="Adicionar ao carrinho"
      >
        <ShoppingCart class="h-4 w-4" />
      </button>
    </div>
  </div>
</template>

// src/components/product/ProductCard.tsx
import { Link } from 'react-router-dom';
import { type Product } from '@/types/product';
import { useLazyImage } from '@/hooks/useLazyImage';
import { Card, CardContent, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ShoppingCart } from 'lucide-react';

interface ProductCardProps {
  product: Product;
}

export function ProductCard({ product }: ProductCardProps) {
  const { imgRef, isInView, isLoaded, setIsLoaded } = useLazyImage(product.image);

  return (
    <Card className="overflow-hidden border-none shadow-sm hover:shadow-md transition-all duration-300 group rounded-2xl bg-white">
      <Link to={`/product/${product.id}`} className="block relative aspect-square overflow-hidden bg-secondary/20">
        {isInView ? (
          <img
            ref={imgRef}
            src={product.image}
            alt={product.name}
            onLoad={() => setIsLoaded(true)}
            className={`w-full h-full object-cover transition-transform duration-500 group-hover:scale-105 ${
              isLoaded ? 'opacity-100' : 'opacity-0'
            }`}
          />
        ) : (
          <div ref={imgRef} className="w-full h-full" />
        )}
        
        {!isLoaded && (
          <div className="absolute inset-0 flex items-center justify-center bg-secondary/10 animate-pulse">
            <span className="text-xs text-muted-foreground">Carregando...</span>
          </div>
        )}

        <Badge className="absolute top-3 left-3 bg-white/90 text-primary border-none text-[10px] uppercase font-bold py-0.5 px-2">
          {product.category}
        </Badge>
      </Link>

      <CardContent className="p-4">
        <Link to={`/product/${product.id}`}>
          <h3 className="font-bold text-base mb-1 line-clamp-1 group-hover:text-primary transition-colors">
            {product.name}
          </h3>
        </Link>
        <p className="text-muted-foreground text-xs line-clamp-2 mb-3 h-8">
          {product.shortDescription}
        </p>
        <div className="flex items-center justify-between">
          <span className="text-lg font-bold text-primary">
            R$ {product.price.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
          </span>
        </div>
      </CardContent>

      <CardFooter className="p-4 pt-0 flex gap-2">
        <Link to={`/product/${product.id}`} className="flex-1">
          <Button variant="outline" className="w-full text-xs rounded-xl h-9 border-primary/20 hover:bg-primary/10 hover:text-primary">
            Ver detalhes
          </Button>
        </Link>
        <Button className="bg-primary text-white hover:bg-primary/90 h-9 w-9 p-0 rounded-xl">
          <ShoppingCart className="h-4 w-4" />
        </Button>
      </CardFooter>
    </Card>
  );
}
