// src/pages/Catalog.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { Search } from 'lucide-vue-next';
import { useProductStore } from '@/store/useProductStore';
import ProductCard from '@/components/product/ProductCard.vue';
import type { SortOption } from '@/types/product';

const route = useRoute();
const router = useRouter();
const productStore = useProductStore();

const search = ref('');
const selectedCategory = ref<string>('All');
const sortBy = ref<SortOption>('alphabetical');

const categories = computed(() => ['All', ...productStore.categories]);
const allProducts = computed(() => productStore.products);

onMounted(() => {
  if (route.query.cat) {
    selectedCategory.value = String(route.query.cat);
  }
  if (route.query.sort) {
    sortBy.value = route.query.sort as SortOption;
  }
  if (route.query.q) {
    search.value = String(route.query.q);
  }
});

watch([selectedCategory, sortBy], () => {
  const query: Record<string, string> = {};
  if (selectedCategory.value !== 'All') query.cat = selectedCategory.value;
  if (sortBy.value !== 'alphabetical') query.sort = sortBy.value;
  if (search.value) query.q = search.value;
  router.replace({ query });
});

const filteredProducts = computed(() => {
  const term = search.value.toLowerCase().trim();
  const cat = selectedCategory.value;

  const result = allProducts.value.filter((p) => {
    const matchesSearch =
      !term ||
      p.name.toLowerCase().includes(term) ||
      p.shortDescription.toLowerCase().includes(term);
    const matchesCat = cat === 'All' || p.category === cat;
    return matchesSearch && matchesCat;
  });

  if (sortBy.value === 'price-asc') {
    result.sort((a, b) => a.price - b.price);
  } else if (sortBy.value === 'price-desc') {
    result.sort((a, b) => b.price - a.price);
  } else if (sortBy.value === 'alphabetical') {
    result.sort((a, b) => a.name.localeCompare(b.name));
  }

  return result;
});
</script>

<template>
  <div class="container mx-auto px-4 py-12">
    <!-- Header -->
    <div class="mb-10">
      <h1 class="text-4xl md:text-5xl font-bold text-primary mb-3">Nossos Produtos</h1>
      <p class="text-muted-foreground">Encontre cosméticos, maquiagens e produtos ideais para você.</p>
    </div>

    <!-- Filters & Search Bar -->
    <div class="flex flex-col md:flex-row gap-4 items-stretch md:items-center justify-between mb-8">
      <!-- Search Input -->
      <div class="relative flex-1 max-w-md">
        <Search class="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
        <input
          v-model="search"
          type="text"
          placeholder="Buscar produtos..."
          class="w-full pl-11 pr-4 py-3 rounded-2xl border border-primary/20 bg-white focus:outline-none focus:ring-2 focus:ring-primary/30 text-sm shadow-sm"
        />
      </div>

      <!-- Sort Dropdown -->
      <div class="flex items-center gap-3">
        <label class="text-xs text-muted-foreground font-semibold whitespace-nowrap">Ordenar por:</label>
        <select
          v-model="sortBy"
          class="py-3 px-4 rounded-2xl border border-primary/20 bg-white text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 shadow-sm cursor-pointer"
        >
          <option value="alphabetical">Nome (A - Z)</option>
          <option value="price-asc">Menor Preço</option>
          <option value="price-desc">Maior Preço</option>
        </select>
      </div>
    </div>

    <!-- Category Pills -->
    <div class="flex items-center gap-2 overflow-x-auto pb-4 mb-8 scrollbar-none">
      <button
        v-for="cat in categories"
        :key="cat"
        type="button"
        @click="selectedCategory = cat"
        class="px-5 py-2.5 rounded-full text-xs font-semibold whitespace-nowrap transition-all duration-200"
        :class="
          selectedCategory === cat
            ? 'bg-primary text-white shadow-md'
            : 'bg-white text-muted-foreground hover:bg-secondary/40 border border-primary/15'
        "
      >
        {{ cat === 'All' ? 'Todos' : cat }}
      </button>
    </div>

    <!-- Counter -->
    <div class="mb-6 text-xs text-muted-foreground font-medium">
      Mostrando {{ filteredProducts.length }} de {{ allProducts.length }} produtos
    </div>

    <!-- Products Grid -->
    <div
      v-if="filteredProducts.length > 0"
      class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"
    >
      <ProductCard
        v-for="prod in filteredProducts"
        :key="prod.id"
        :product="prod"
      />
    </div>

    <!-- Empty State -->
    <div
      v-else
      class="text-center py-20 bg-white rounded-3xl border border-primary/10 shadow-sm p-8"
    >
      <p class="text-xl font-bold text-primary mb-2">Nenhum produto encontrado</p>
      <p class="text-sm text-muted-foreground mb-6">Tente ajustar os filtros ou a sua busca.</p>
      <button
        type="button"
        @click="search = ''; selectedCategory = 'All'"
        class="px-6 py-3 rounded-xl bg-primary text-white hover:bg-primary/90 text-sm font-semibold transition-colors"
      >
        Limpar Filtros
      </button>
    </div>
  </div>
</template>

// src/pages/Catalog.tsx
import { useState, useMemo } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useProductStore } from '@/store/useProductStore';
import { ProductCard } from '@/components/product/ProductCard';
import { SEO } from '@/components/SEO';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { type Category, type SortOption } from '@/types/product';
import { Search, FilterX } from 'lucide-react';


export function Catalog() {
  const [searchParams, setSearchParams] = useSearchParams();
  const products = useProductStore((state) => state.products);
  const storeCategories = useProductStore((state) => state.categories);
  const CATEGORIES = ["All", ...storeCategories];
  
  const [search, setSearch] = useState("");
  const currentCategory = (searchParams.get("cat") as Category | "All") || "All";
  const sortBy = (searchParams.get("sort") as SortOption) || "alphabetical";

  const filteredProducts = useMemo(() => {
    let result = products.filter((p) => {
      const matchesSearch = p.name.toLowerCase().includes(search.toLowerCase());
      const matchesCategory = currentCategory === "All" || p.category === currentCategory;
      return matchesSearch && matchesCategory;
    });

    if (sortBy === "price-asc") {
      result.sort((a, b) => a.price - b.price);
    } else if (sortBy === "price-desc") {
      result.sort((a, b) => b.price - a.price);
    } else if (sortBy === "alphabetical") {
      result.sort((a, b) => a.name.localeCompare(b.name));
    }

    return result;
  }, [products, search, currentCategory, sortBy]);

  const handleCategoryChange = (cat: string) => {
    setSearchParams((prev) => {
      if (cat === "All") prev.delete("cat");
      else prev.set("cat", cat);
      return prev;
    });
  };

  const handleSortChange = (sort: SortOption) => {
    setSearchParams((prev) => {
      prev.set("sort", sort);
      return prev;
    });
  };

  const resetFilters = () => {
    setSearch("");
    setSearchParams({});
  };

  return (
    <>
      <SEO title="Catálogo - Todos os Produtos" />
      
      <section className="py-12 bg-secondary/10">
        <div className="container mx-auto px-4">
          <h1 className="text-4xl font-bold text-primary mb-8">Nossos Produtos</h1>
          
          {/* Filters Bar */}
          <div className="flex flex-col lg:flex-row gap-4 mb-10 items-end lg:items-center">
            <div className="relative w-full lg:max-w-xs">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input 
                placeholder="Buscar produtos..." 
                className="pl-10 rounded-xl border-primary/20 bg-white"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>

            <div className="flex gap-4 w-full lg:w-auto overflow-x-auto pb-2 lg:pb-0 scrollbar-hide">
              {CATEGORIES.map((cat) => (
                <Button
                  key={cat}
                  variant={currentCategory === cat ? "default" : "outline"}
                  className={`rounded-full whitespace-nowrap px-6 h-10 ${
                    currentCategory === cat ? 'bg-primary text-white' : 'border-primary/20 text-primary hover:bg-primary/5'
                  }`}
                  onClick={() => handleCategoryChange(cat)}
                >
                  {cat === "All" ? "Todos" : cat}
                </Button>
              ))}
            </div>

            <div className="ml-auto w-full lg:w-48">
              <Select value={sortBy} onValueChange={(val: SortOption | null) => { if (val) handleSortChange(val) }}>
                <SelectTrigger className="rounded-xl border-primary/20 bg-white text-primary">
                  <SelectValue placeholder="Ordenar por" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="alphabetical">Ordem Alfabética</SelectItem>
                  <SelectItem value="price-asc">Menor Preço</SelectItem>
                  <SelectItem value="price-desc">Maior Preço</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Results Info */}
          <div className="flex items-center justify-between mb-6">
            <p className="text-sm text-muted-foreground">
              Mostrando {filteredProducts.length} de {products.length} produtos
            </p>
            {(search || currentCategory !== "All" || sortBy !== "alphabetical") && (
              <Button variant="ghost" size="sm" onClick={resetFilters} className="text-xs text-primary hover:text-primary/80">
                <FilterX className="mr-2 h-3 w-3" /> Limpar filtros
              </Button>
            )}
          </div>

          {/* Products Grid */}
          {filteredProducts.length > 0 ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-8">
              {filteredProducts.map((product) => (
                <ProductCard key={product.id} product={product} />
              ))}
            </div>
          ) : (
            <div className="text-center py-24 bg-white rounded-3xl border border-dashed border-primary/20">
              <h3 className="text-xl font-bold text-primary mb-2">Nenhum produto encontrado</h3>
              <p className="text-muted-foreground">Tente ajustar sua busca ou filtros.</p>
              <Button onClick={resetFilters} variant="link" className="text-primary mt-4">
                Voltar para o catálogo completo
              </Button>
            </div>
          )}
        </div>
      </section>
    </>
  );
}
